# Generated by Django 5.0.2 on 2024-02-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgenre',
            name='genre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
