# Generated by Django 5.0.6 on 2024-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0002_alter_postgenre_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='created',
        ),
    ]
