# Generated by Django 5.0.6 on 2024-11-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0003_rename_date_created_post_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttags',
            old_name='title',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='No Name', max_length=50),
        ),
    ]
