# Generated by Django 5.0.6 on 2024-11-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_userprofilewriter_total_dislikes_counter'),
        ('Stories', '0004_rename_title_posttags_tag_alter_post_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userviewedposts',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='userviewedposts',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views_counter',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='story_dislikes', to='Authentication.baseuserprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='story_likes', to='Authentication.baseuserprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(related_name='story_views', to='Authentication.baseuserprofile'),
        ),
        migrations.DeleteModel(
            name='UserLikedPosts',
        ),
        migrations.DeleteModel(
            name='UserViewedPosts',
        ),
    ]
