# Generated by Django 5.0.6 on 2024-11-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0005_remove_userviewedposts_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
    ]
