# Generated by Django 5.0.6 on 2024-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0006_remove_post_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='No Name', max_length=50, unique=True),
        ),
    ]
