# Generated by Django 5.0.2 on 2024-02-29 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes_count', models.PositiveBigIntegerField(default=0)),
                ('dislikes_count', models.PositiveBigIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.baseuserprofile')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comments.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stories.post')),
            ],
        ),
    ]
