# Generated by Django 5.0.6 on 2024-11-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_created',
            new_name='created',
        ),
    ]
