# Generated by Django 5.0.6 on 2024-11-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_rename_date_created_comment_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='parent_comment_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='story_id',
        ),
    ]
