# Generated by Django 5.0.6 on 2024-11-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_userprofilewriter_total_dislikes_counter'),
        ('Comments', '0003_rename_creator_comment_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.baseuserprofile'),
        ),
    ]
