# Generated by Django 5.0.2 on 2024-02-29 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stories_viewed', models.PositiveBigIntegerField(default=0)),
                ('total_comments_made', models.PositiveBigIntegerField(default=0)),
                ('total_liked_comments', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_pseudo', models.CharField(default='User-73058842 Author', max_length=100)),
                ('subscribers_counter', models.PositiveBigIntegerField(default=0)),
                ('total_likes_counter', models.PositiveBigIntegerField(default=0)),
                ('total_story_views_counter', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTimeStampThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_subscribed', models.DateTimeField(default=django.utils.timezone.now)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userprofilereader')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userprofilewriter')),
            ],
        ),
        migrations.AddField(
            model_name='userprofilereader',
            name='subscribed_to',
            field=models.ManyToManyField(through='Authentication.SubscriptionTimeStampThrough', to='Authentication.userprofilewriter'),
        ),
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/')),
                ('displayable_name', models.CharField(default='User-59402040', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.userprofilereader')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.userprofilewriter')),
            ],
        ),
    ]
