# Generated by Django 5.0.2 on 2024-02-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserprofile',
            name='displayable_name',
            field=models.CharField(default='User-94933450', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofilewriter',
            name='writer_pseudo',
            field=models.CharField(default='User-69650794 Author', max_length=100),
        ),
    ]
