# Generated by Django 5.0.6 on 2024-11-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_userprofilewriter_total_dislikes_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilereader',
            name='total_comments_made',
        ),
        migrations.RemoveField(
            model_name='userprofilereader',
            name='total_liked_comments',
        ),
        migrations.RemoveField(
            model_name='userprofilereader',
            name='total_stories_viewed',
        ),
        migrations.RemoveField(
            model_name='userprofilewriter',
            name='total_dislikes_counter',
        ),
        migrations.RemoveField(
            model_name='userprofilewriter',
            name='total_likes_counter',
        ),
        migrations.RemoveField(
            model_name='userprofilewriter',
            name='total_story_views_counter',
        ),
    ]
